/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.Vista;

import ec.ups.edu.Controlador.Conexion;
import ec.ups.edu.Controlador.ControladorAsignatura;
import ec.ups.edu.Controlador.ControladorDocente;
import ec.ups.edu.Controlador.ControladorEspacioFisico;
import ec.ups.edu.Controlador.ControladorEspecialidad;
import ec.ups.edu.Controlador.ControladorEstudiante;
import ec.ups.edu.Controlador.ControladorGrupo;
import ec.ups.edu.Controlador.ControladorHorario;
import ec.ups.edu.Controlador.ControladorMatricula;
import ec.ups.edu.Controlador.ControladorModalidad;
import ec.ups.edu.Controlador.ControladorNivelAsignatura;
import ec.ups.edu.Controlador.ControladorPeriodoLectivo;
import ec.ups.edu.Controlador.ControladorUsuario;

/**
 *
 * @author 59396
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ControladorUsuario controladorUsuario;
    private ControladorEstudiante controladorEstudiante;
    private ControladorDocente controladorDocente;
    private Conexion conexion;
    private ControladorNivelAsignatura controladorNivelAsignatura;
    private ControladorAsignatura controladorAsignatura;
    private ControladorEspacioFisico controladorEspacioFisico;
    private ControladorEspecialidad controladorEspecialidad;
    private ControladorPeriodoLectivo controladorPeriodoLectivo;
    private ControladorGrupo controladorGrupo;
    private ControladorHorario controladorHorario;
    private ControladorModalidad controladorModalidad;
    private ControladorMatricula controladorMatricula;

    public Principal() {
        initComponents();
        conexion = new Conexion();
        controladorUsuario = new ControladorUsuario();
        controladorNivelAsignatura = new ControladorNivelAsignatura(conexion);
        controladorAsignatura = new ControladorAsignatura(conexion);
        controladorDocente = new ControladorDocente(conexion);
        controladorEstudiante = new ControladorEstudiante(conexion);
        controladorEspacioFisico = new ControladorEspacioFisico(conexion);
        controladorEspecialidad = new ControladorEspecialidad(conexion);
        controladorPeriodoLectivo = new ControladorPeriodoLectivo(conexion);
        controladorGrupo = new ControladorGrupo(conexion);
        controladorHorario = new ControladorHorario(conexion);
        controladorModalidad = new ControladorModalidad(conexion);
        controladorMatricula = new ControladorMatricula(conexion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        estMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        docMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        nivelaMenuItem = new javax.swing.JMenuItem();
        asMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        espafMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem3 = new javax.swing.JMenuItem();
        aboutMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar1.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("USUARIO");

        jMenu1.setText("ESTUDIANTE");

        estMenuItem.setMnemonic('o');
        estMenuItem.setText("CREAR");
        estMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(estMenuItem);

        fileMenu.add(jMenu1);

        jMenu2.setText("DOCENTE");

        docMenuItem.setMnemonic('s');
        docMenuItem.setText("CREAR");
        docMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(docMenuItem);

        jMenuItem2.setText("BUSCAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("EDITAR");
        jMenu2.add(jMenuItem3);

        fileMenu.add(jMenu2);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("ASIGNATURA");

        nivelaMenuItem.setMnemonic('t');
        nivelaMenuItem.setText("NIVEL ASIGNATURA");
        nivelaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(nivelaMenuItem);

        asMenuItem.setMnemonic('y');
        asMenuItem.setText("ASIGNATURA");
        asMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(asMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("GRUPO");

        espafMenuItem.setMnemonic('c');
        espafMenuItem.setText("ESPACIO FISICO");
        espafMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espafMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(espafMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("ESPECIALIDAD");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        aboutMenuItem1.setMnemonic('a');
        aboutMenuItem1.setText("PERIODO LECTIVO");
        aboutMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem1);

        aboutMenuItem3.setMnemonic('a');
        aboutMenuItem3.setText("HORARIO");
        aboutMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem3);

        aboutMenuItem2.setMnemonic('a');
        aboutMenuItem2.setText("CREAR GRUPO");
        aboutMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem2ActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem2);

        menuBar.add(helpMenu);

        jMenu6.setText("MATRICULA");

        jMenuItem4.setText("MODALIDAD ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("MATRICULA");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        menuBar.add(jMenu6);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        conexion.desconectar();
        System.exit(0);

    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void estMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estMenuItemActionPerformed
        // TODO add your handling code here:

        VistaControladorEstudiante vista = new VistaControladorEstudiante(controladorEstudiante, controladorUsuario);
        jDesktopPane1.add(vista);
        vista.setVisible(true);


    }//GEN-LAST:event_estMenuItemActionPerformed

    private void docMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docMenuItemActionPerformed
        // TODO add your handling code here:

        VistaControladorDocente vista = new VistaControladorDocente(controladorDocente, controladorUsuario);
        jDesktopPane1.add(vista);
        vista.setVisible(true);


    }//GEN-LAST:event_docMenuItemActionPerformed

    private void nivelaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelaMenuItemActionPerformed
        // TODO add your handling code here:

        VistaNivelAsignatura vista = new VistaNivelAsignatura(controladorNivelAsignatura);
        jDesktopPane1.add(vista);
        vista.setVisible(true);

    }//GEN-LAST:event_nivelaMenuItemActionPerformed

    private void asMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asMenuItemActionPerformed
        // TODO add your handling code here:

        VistaAsginatura vista = new VistaAsginatura(controladorAsignatura, controladorNivelAsignatura);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_asMenuItemActionPerformed

    private void espafMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espafMenuItemActionPerformed
        // TODO add your handling code here:
        VistaEspacioFisico vista = new VistaEspacioFisico(controladorEspacioFisico);
        jDesktopPane1.add(vista);
        vista.setVisible(true);

    }//GEN-LAST:event_espafMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        VistaEspecialidad vista = new VistaEspecialidad(controladorEspecialidad);
        jDesktopPane1.add(vista);
        vista.setVisible(true);

    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void aboutMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem1ActionPerformed
        // TODO add your handling code here:
        VistaPeriiodoLectivo vista = new VistaPeriiodoLectivo(controladorPeriodoLectivo);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem1ActionPerformed

    private void aboutMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem2ActionPerformed
        // TODO add your handling code here:
        VistaCrearGrupo vista = new VistaCrearGrupo(controladorGrupo, controladorAsignatura, controladorDocente,
                controladorEspacioFisico, controladorNivelAsignatura, controladorHorario);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem2ActionPerformed

    private void aboutMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem3ActionPerformed
        // TODO add your handling code here:
        VistaHorario vista = new VistaHorario(controladorHorario);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_aboutMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VistaBuscarDocente vista = new VistaBuscarDocente(controladorDocente);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        VistaModalidad vista = new VistaModalidad(controladorModalidad);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        VistaMatricula vista = new VistaMatricula(controladorMatricula, controladorModalidad, 
                controladorEspecialidad, controladorPeriodoLectivo, controladorGrupo, controladorEstudiante);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem aboutMenuItem2;
    private javax.swing.JMenuItem aboutMenuItem3;
    private javax.swing.JMenuItem asMenuItem;
    private javax.swing.JMenuItem docMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem espafMenuItem;
    private javax.swing.JMenuItem estMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nivelaMenuItem;
    // End of variables declaration//GEN-END:variables

}
