/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.Vista;

import ec.ups.edu.Controlador.Conexion;
import ec.ups.edu.Controlador.ControladorAsignatura;
import ec.ups.edu.Controlador.ControladorDocente;
import ec.ups.edu.Controlador.ControladorEstudiante;
import ec.ups.edu.Controlador.ControladorNivelAsignatura;
import ec.ups.edu.Controlador.ControladorUsuario;

/**
 *
 * @author 59396
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ControladorUsuario controladorUsuario;
    private ControladorEstudiante controladorEstudiante;
    private ControladorDocente controladorDocente;
    private Conexion conexion;
    private ControladorNivelAsignatura controladorNivelAsignatura;
    private ControladorAsignatura controladorAsignatura;

    public Principal() {
        initComponents();
        conexion = new Conexion();
        controladorUsuario = new ControladorUsuario();
        controladorNivelAsignatura = new ControladorNivelAsignatura(conexion);
        controladorAsignatura = new ControladorAsignatura(conexion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        estMenuItem = new javax.swing.JMenuItem();
        docMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        nivelaMenuItem = new javax.swing.JMenuItem();
        asMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("USUARIO");

        estMenuItem.setMnemonic('o');
        estMenuItem.setText("ESTUDIANTE");
        estMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(estMenuItem);

        docMenuItem.setMnemonic('s');
        docMenuItem.setText("DOCENTE");
        docMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(docMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("ASIGNATURA");

        nivelaMenuItem.setMnemonic('t');
        nivelaMenuItem.setText("NIVEL ASIGNATURA");
        nivelaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(nivelaMenuItem);

        asMenuItem.setMnemonic('y');
        asMenuItem.setText("ASIGNATURA");
        asMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(asMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        conexion.desconectar();
        System.exit(0);

    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void estMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estMenuItemActionPerformed
        // TODO add your handling code here:
        controladorEstudiante = new ControladorEstudiante(conexion);
        VistaControladorEstudiante vista = new VistaControladorEstudiante(controladorEstudiante, controladorUsuario);
        jDesktopPane1.add(vista);
        vista.setVisible(true);


    }//GEN-LAST:event_estMenuItemActionPerformed

    private void docMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docMenuItemActionPerformed
        // TODO add your handling code here:
        controladorDocente = new ControladorDocente(conexion);
        VistaControladorDocente vista = new VistaControladorDocente(controladorDocente, controladorUsuario);
        jDesktopPane1.add(vista);
        vista.setVisible(true);


    }//GEN-LAST:event_docMenuItemActionPerformed

    private void nivelaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelaMenuItemActionPerformed
        // TODO add your handling code here:
        
        VistaNivelAsignatura vista = new VistaNivelAsignatura(controladorNivelAsignatura);
        jDesktopPane1.add(vista);
        vista.setVisible(true);

    }//GEN-LAST:event_nivelaMenuItemActionPerformed

    private void asMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asMenuItemActionPerformed
        // TODO add your handling code here:
        
        VistaAsginatura vista = new VistaAsginatura(controladorAsignatura, controladorNivelAsignatura);
        jDesktopPane1.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_asMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem asMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem docMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem estMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nivelaMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    // End of variables declaration//GEN-END:variables

}
